# DOCKERFILE
# Purpose: packages the harness so it runs the same anywhere: Docker locally, Kubernetes (kind), later AKS.
# Default command runs the free mock evaluation; secrets are never in the image (see .dockerignore).
# Authorship: generated by Claude Opus 5.5 (Anthropic); reviewed by Connor.

# Base: slim official Python image, same major version as local development
FROM python:3.13-slim

# Working folder inside the container
WORKDIR /app

# Install the package first (changes rarely, so Docker caches this layer)
COPY pyproject.toml README.md ./
COPY src ./src
RUN pip install --no-cache-dir ".[azure]"

# Copy config and data the harness reads at run time
COPY config ./config
COPY data ./data

# Run as a non-root user (security good practice; Kubernetes clusters often require it)
RUN useradd --create-home app && chown -R app /app
USER app

# llm-eval is the command; default arguments run the mock evaluation
ENTRYPOINT ["llm-eval"]
CMD ["run", "--provider", "mock"]
